<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="108531" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:51 IST">
    <groups>
    </groups>
    <test name="FourTest" duration-ms="101642" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:45 IST">
      <class name="com.tests.FourTest">
        <test-method status="FAIL" signature="fourTest()[pri:0, instance:com.tests.FourTest@38c6f217]" name="fourTest" duration-ms="92073" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:35 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.tests.FourTest.fourTest(FourTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fourTest -->
        <test-method status="PASS" signature="closure()[pri:0, instance:com.tests.FourTest@38c6f217]" name="closure" is-config="true" duration-ms="9234" started-at="2023-06-03T20:59:35 IST" finished-at="2023-06-03T20:59:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- com.tests.FourTest -->
    </test> <!-- FourTest -->
    <test name="TwoTest" duration-ms="101642" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:45 IST">
      <class name="com.tests.TwoTest">
        <test-method status="FAIL" signature="testTwo()[pri:0, instance:com.tests.TwoTest@3835c46]" name="testTwo" duration-ms="89012" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:32 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.tests.TwoTest.testTwo(TwoTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method status="PASS" signature="closure()[pri:0, instance:com.tests.TwoTest@3835c46]" name="closure" is-config="true" duration-ms="11435" started-at="2023-06-03T20:59:33 IST" finished-at="2023-06-03T20:59:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- com.tests.TwoTest -->
    </test> <!-- TwoTest -->
    <test name="ThreeTest" duration-ms="101640" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:45 IST">
      <class name="com.tests.ThreeTest">
        <test-method status="FAIL" signature="threeTest()[pri:0, instance:com.tests.ThreeTest@16293aa2]" name="threeTest" duration-ms="85329" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:28 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.tests.ThreeTest.threeTest(ThreeTest.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threeTest -->
        <test-method status="PASS" signature="closure()[pri:0, instance:com.tests.ThreeTest@16293aa2]" name="closure" is-config="true" duration-ms="15101" started-at="2023-06-03T20:59:29 IST" finished-at="2023-06-03T20:59:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- com.tests.ThreeTest -->
    </test> <!-- ThreeTest -->
    <test name="LoginTest" duration-ms="108427" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:51 IST">
      <class name="com.tests.LoginTest">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:com.tests.LoginTest@223d2c72]" name="openApplication" is-config="true" duration-ms="100121" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="PASS" signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.tests.LoginTest@223d2c72]" name="login" duration-ms="7089" started-at="2023-06-03T20:59:43 IST" data-provider="getLoginData" finished-at="2023-06-03T20:59:50 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[akashkadari3696@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Mar!2023!!]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Successfull]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.tests.LoginTest@223d2c72]" name="tearDown" is-config="true" duration-ms="1144" started-at="2023-06-03T20:59:50 IST" finished-at="2023-06-03T20:59:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.LoginTest -->
    </test> <!-- LoginTest -->
    <test name="RegisterTest" duration-ms="108530" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:51 IST">
      <class name="com.tests.RegisterTest">
        <test-method status="PASS" signature="register()[pri:0, instance:com.tests.RegisterTest@131774fe]" name="register" duration-ms="107791" started-at="2023-06-03T20:58:03 IST" finished-at="2023-06-03T20:59:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="closure()[pri:0, instance:com.tests.RegisterTest@131774fe]" name="closure" is-config="true" duration-ms="658" started-at="2023-06-03T20:59:51 IST" finished-at="2023-06-03T20:59:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- com.tests.RegisterTest -->
    </test> <!-- RegisterTest -->
  </suite> <!-- Suite -->
</testng-results>
